name = "SurrogatesBase"
uuid = "89f642e6-4179-4274-8202-c11f4bd9a72c"
authors = ["Samuel Belko <samuelbelko@protonmail.com> and contributors"]
version = "1.1.0"

[compat]
Aqua = "0.8"
LinearAlgebra = "1.10"
SafeTestsets = "0.1"
Statistics = "1.10"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "LinearAlgebra", "SafeTestsets", "Statistics", "Test"]
