name = "SurrogatesBase"
uuid = "89f642e6-4179-4274-8202-c11f4bd9a72c"
authors = ["Samuel Belko <samuelbelko@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
